data:
  build: docker/data
  hostname: data
  domainname: data.tw.rpi.edu

postgres:
  build: docker/postgres
  hostname: postgres
  domainname: data.tw.rpi.edu
  ports:
    - "127.0.0.1:15432:5432"
  volumes_from:
    - data
  environment:
    - CKAN_PASS=rds!test!123
    - DATASTORE_PASS=rds!test!123

solr:
  build: docker/solr
  hostname: solr
  domainname: data.tw.rpi.edu
  ports:
    - "127.0.0.1:18983:8983"
  volumes:
    - ./_src/ckan/ckan/config/solr/schema.xml:/opt/solr/example/solr/ckan/conf/schema.xml

datapusher:
  build: _service-provider/_datapusher
  hostname: datapusher
  domainname: data.tw.rpi.edu
  ports:
    - "127.0.0.1:18800:8800"

ckan:
  build: .
  hostname: ckan
  domainname: data.tw.rpi.edu
  ports:
    - "127.0.0.1:12222:22"
    - "127.0.0.1:15000:5000"
    - "127.0.0.1:18080:80"
  links:
    - postgres:postgres
    - solr:solr
    - datapusher:datapusher
  command: /sbin/my_init --enable-insecure-key
  volumes_from:
    - data
  volumes:
    - ./_src:/usr/lib/ckan/default/src
    - ./_etc/ckan/custom_options.ini:/etc/ckan/default/custom_options.ini
    - ./_etc/supervisor/conf.d:/etc/supervisor/conf.d

nginx:
  build: docker/nginx
  hostname: nginx
  domainname: data.tw.rpi.edu
  links:
    - ckan:ckan
  ports:
    - "127.0.0.1:10080:80"
  volumes:
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf



